config:
  project_repos:
    myrepo:
      repo: 'https://github.com/EOSC-synergy/sqaaas-web.git'

sqa_criteria:
  qc_doc:
    repos:
      worsica-cicd:
        container: myrepo-testing-host
        commands:
          - git clone https://github.com/EOSC-synergy/sqaaas-web.git
          - cd sqaaas-web
          - |
            echo 'module.exports = {
                provider_url: "https://aai-dev.egi.eu",
                client_id: "10333f08-7e8f-4cc4-bba0-e66f4e5505d0",
                redirect_uri: "https://eosc-synergy.github.io/sqaaas-web/callback",
                url_authorize: "https://aai-dev.egi.eu/oidc/authorize",
                url_user_info: "https://aai-dev.egi.eu/oidc/userinfo",
            }' > src/env.js (editado) 
          - git checkout master
          - npm run build
          - git checkout gh-pages
          - cd dist/
          - cp -R * ../
          - cd ..
          - git add *
          - git commit -m "Updating web in gh-pages branch"
          - git push -u origin gh-pages