config:
  project_repos:
    sqaas-web:
      repo: 'https://github.com/EOSC-synergy/sqaaas-web.git'
      branch: jpl-branch
      dockerhub: dianamnaranjo/sqaaas-jpl
      dockertag: latest

sqa_criteria:
  qc_doc:
    repos:
      sqaas-web:
        container: testing-jpl-sqaaas
        commands:
          - sh /testing-jpl-sqaaas/script.sh
          