config:
  credentials:
      - id: userpass_sqaaas_web
        username_var: GIT_USER
        password_var: GIT_PASSWORD

sqa_criteria:
  qc_doc:
    repos:
      sqaaas-web:
        container: testing-jpl-sqaaas
        commands:
          - env
          - ls -la /testing
          - /testing/.git_credential_helper.sh get
          - sh /testing/script2.sh
