config:
  project_repos:
    sqaas-web:
      repo: 'https://github.com/EOSC-synergy/sqaaas-web.git'
      branch: jpl-branch      

sqa_criteria:
  qc_doc:
    repos:
      sqaas-web:
        container: testing-jpl-sqaaas
        commands:
          - ls -l
          - sh /testing-jpl-sqaaas/sqaaas-web/script.sh
          