config:
  project_repos:
    sqaas-web:
      repo: 'https://github.com/EOSC-synergy/sqaaas-web.git'
      branch: jpl-branch
      credentials_id: userpass_sqaaas_web
  credentials:
      - id: userpass_sqaaas_web
        username_var: GIT_USER
        password_var: GIT_PASSWORD

sqa_criteria:
  qc_doc:
    repos:
      sqaas-web:
        container: testing-jpl-sqaaas
        commands:
          - ls -a /testing-jpl-sqaaas
          - sh /testing-jpl-sqaaas/script.sh
