version: "3.6"

services:
  testing-jpl-sqaaas:
    image: "ubuntu:16.04"
    container_name: testing-jpl-sqaaas
    hostname: "jpl-sqaaas-testing"
    volumes:
     - type: bind
       source: ./
       target: /jpl-sqaaas-testing
